name: Publish image
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push image to multiple registries
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      -
        name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        run: |
            cd docker
            make 
      -
        name: push
        run: |
            docker images
            docker push ghcr.io/freddodd6/ub-12.04-base:latest
            docker push ghcr.io/freddodd6/ub-16.04-base:latest
            docker push ghcr.io/freddodd6/ub-18.04-base:latest
            docker push ghcr.io/freddodd6/ub-12.04-conda:latest
            docker push ghcr.io/freddodd6/ub-16.04-irods-4.2.7:latest
            # missing 18.04 irods temporarily
